sonar.projectKey=crifredes-svg_Calidad-de-software-
sonar.organization=crifredes-svg

sonar.sources=.
sonar.exclusions=venv/**,tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml